replicaCount: 1

image:
  repository: sj2012/time-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 80

serviceAccount:
  create: true
  name: ''

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
